### ISSUE TITLE
ePub is inserted in the Volume and Issue fields, however ePub is not inserted into the Pages field.

### ISSUE THREAD

**Issue by SafetyLit** [retorquere/zotero-safetylit-mods#3]
The new MODS export works well except for one problem: although ePub is inserted in the Volume and Issue fields, however, ePub is not inserted into the Pages field.

**Comment by retorquere** [comment]
New translator is up

**Comment by retorquere** [comment]
does this fix the problem?

**Comment by SafetyLit** [comment]
This issue should be replaced by issue 4.
